#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests..."
npm test

if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi

echo "Running build..."
npm run build

if [ $? -ne 0 ]; then
  echo "Build failed. Push aborted."
  exit 1
fi

echo "All checks passed."